FROM amazoncorretto:8u402-alpine3.19
LABEL maintainer="qkssk1711@163.com"
ENV TZ=Asia/Shanghai
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache ttf-dejavu