name: Publish 8u432-alpine3.20

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/base.yml
    with:
      base_image_tag: 8u432-alpine3.20
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}