name: Publish amazoncorretto:8u402-alpine3.19

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/base.yml
    with:
      dockerfile: ./Dockerfile.amazoncorretto
      base_image_name: amazoncorretto
      base_image_tag: 8u402-alpine3.19
      release_image_name: kit101z/amazoncorretto
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}