name: Publish 17.0.14-alpine3.21

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  RELEASE_IMAGE_NAME: kit101z/amazoncorretto
  BASE_IMAGE_NAME: amazoncorretto
  BASE_IMAGE_TAG: 17.0.14-alpine3.21

jobs:
  build:
    uses: ./.github/workflows/base.yml
    with:
      base_image_tag: 17.0.14-alpine3.21
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}